pool:
  vmImage: "ubuntu-20.04"

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
  - task: SonarCloudPrepare@1
    displayName: 'Prepare analysis configuration'
    inputs:
      SonarCloud: 'SonarCloudKaizimmerm'
      organization: 'kaizimmerm'
      scannerMode: Other
  - task: Cache@2
    displayName: Cache Maven local repo
    inputs:
      key: 'maven | **/pom.xml'
      path: $(MAVEN_CACHE_FOLDER)    
  
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'AzureKaizimmerm'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az --version
        az account show
    displayName: "Setup CosmosDB gremlin database for integration test"
  - task: Maven@3
    displayName: 'Maven verify and integration-test'
    inputs:
      mavenPomFile: "pom.xml"
      mavenOptions: "-Xmx3072m"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.11"
      jdkArchitectureOption: "x64"
      publishJUnitResults: true
      sonarQubeRunAnalysis: true
      sqMavenPluginVersionChoice: 'latest'
      codeCoverageToolOption: 'JaCoCo'
      testResultsFiles: "**/surefire-reports/TEST-*.xml"
      goals: "verify integration-test $(MAVEN_OPTS)"
  - task: SonarCloudPublish@1
    displayName: 'Publish results on build summary'
    inputs:
      pollingTimeoutSec: '300'
