pool:
  vmImage: "ubuntu-20.04"

variables:
  - name: mavenCacheFolder
    value: $(Pipeline.Workspace)/.m2/repository
  - name: mavenCacheOpts
    value: '-Dmaven.repo.local=$(mavenCacheFolder)'
  - name: intTestResourceGroup
    value:  'kaizimmerm'
  - name: intTestCosmosAccount
    value:  'kaizimmerm-sample'
  - name: intTestCosmosDbName
    value:  'test$(Build.BuildId)'
  - name: intTestCosmosCollectionName
    value:  'sample-graph'
  - name: intTestCosmosUsername
    value: '/dbs/$(intTestCosmosDbName)/colls/$(intTestCosmosCollectionName)'
  - name: intTestCosmosEndpoint
    value:  $(intTestCosmosAccount).gremlin.cosmos.azure.com

steps:
  - task: SonarCloudPrepare@1
    displayName: 'Prepare analysis configuration'
    inputs:
      SonarCloud: 'SonarCloudKaizimmerm'
      organization: 'kaizimmerm'
      scannerMode: Other
  - task: Cache@2
    displayName: Cache Maven local repo
    inputs:
      key: 'maven | **/pom.xml'
      path: $(mavenCacheFolder)    
  - task: AzureCLI@2
    displayName: "Setup CosmosDB gremlin database for integration test"
    inputs:
      azureSubscription: 'AzureKaizimmerm'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az cosmosdb gremlin database create --account-name $(intTestCosmosAccount) \
          --name $(intTestCosmosDbName) --resource-group $(intTestResourceGroup)
        az cosmosdb gremlin graph create --account-name $(intTestCosmosAccount) \
          --database-name $(intTestCosmosDbName) --name $(intTestCosmosCollectionName) \
          --partition-key-path "/address" --resource-group $(intTestResourceGroup)
  - task: AzureCLI@2
    displayName: "Retrieve CosmosDB key for integration test"
    inputs:
      azureSubscription: 'AzureKaizimmerm'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        keyCosmos=`az cosmosdb keys list --name $(intTestCosmosAccount) \
                --resource-group $(intTestResourceGroup) --query primaryMasterKey -o tsv`
        echo "##vso[task.setvariable variable=intTestCosmosKey;issecret=true]$keyCosmos"
  - task: Maven@3
    displayName: 'Maven verify and integration-test'
    inputs:
      mavenPomFile: "pom.xml"
      mavenOptions: "-Xmx3072m"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.11"
      jdkArchitectureOption: "x64"
      publishJUnitResults: true
      sonarQubeRunAnalysis: true
      sqMavenPluginVersionChoice: 'latest'
      codeCoverageToolOption: 'JaCoCo'
      testResultsFiles: "**/surefire-reports/TEST-*.xml"
      goals: "verify -Pintegration-test -Dgremlin.endpoint=$(intTestCosmosEndpoint) -Dgremlin.username=$(intTestCosmosUsername) -Dgremlin.password=$(intTestCosmosKey) $(mavenCacheOpts)"
    env:
      COSMOS_KEY: $(intTestCosmosKey)
  - task: AzureCLI@2
    displayName: "Delete CosmosDB gremlin database from integration test"
    condition: succeededOrFailed()
    inputs:
      azureSubscription: 'AzureKaizimmerm'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az cosmosdb gremlin database delete --account-name $(intTestCosmosAccount) \
          --name $(intTestCosmosDbName) --resource-group $(intTestResourceGroup) --yes    
  - task: SonarCloudPublish@1
    displayName: 'Publish results on build summary'
    inputs:
      pollingTimeoutSec: '300'
