#
# Copyright (c) 2020 Microsoft and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#

# Build your hawkBit Extensions and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/java
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
# https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#maven

pool:
  vmImage: "ubuntu-latest"

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
  - task: SonarCloudPrepare@1
    displayName: 'Prepare analysis configuration'
    inputs:
      SonarCloud: 'SonarCloudKaizimmerm'
      organization: 'kaizimmerm'
      scannerMode: Other
  - task: Cache@2
    displayName: Cache Maven local repo
    inputs:
      key: 'maven | **/pom.xml'
      path: $(MAVEN_CACHE_FOLDER)    
  - task: Maven@3
    displayName: 'Maven verify'
    inputs:
      mavenPomFile: "pom.xml"
      mavenOptions: "-Xmx3072m"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.11"
      jdkArchitectureOption: "x64"
      publishJUnitResults: true
      sonarQubeRunAnalysis: true
      sqMavenPluginVersionChoice: 'latest'
      codeCoverageToolOption: 'JaCoCo'
      testResultsFiles: "**/surefire-reports/TEST-*.xml"
      goals: "install $(MAVEN_OPTS)"
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'AzureKaizimmerm'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az --version
        az account show
    displayName: "Setup CosmosDB gremlin database for integration test"

  - task: SonarCloudPublish@1
    displayName: 'Publish results on build summary'
    inputs:
      pollingTimeoutSec: '300'
